### ISSUE TITLE
TON trademark for all

### ISSUE THREAD

**Issue by tolya-yanot** [ton-blockchain/TIPs#36]
Dear Telegram Team @TelegramMessenger,

This open letter is written on behalf of the TON Community. 

As you know, our community represents independent open-source developers and blockchain enthusiasts who keep developing the original TON technology. We are proud that you have decided to hand over the original [TON domain](https://ton.org) and [repository](https://github.com/ton-blockchain) to us; it is a great backing to our efforts.

However, a while ago we found out that TON Ventures LTD incorporated in the British Virgin Islands registered trademarks with the term “TON” in several jurisdictions and now actively tries to block our initiatives related to the TON development. Members of our community were notified by Apple Store and GooglePlay that TON Ventures demands that their wallet applications should be removed from the stores. As these apps do contain the word “TON” in their names and interfaces, TON Ventures claims a copyright infringement.

It was in 2018 that Telegram invented and introduced the “TON” trademark in the blockchain domain, and we believe that Telegram allowed the “TON” trademark to be freely used by any product based on that technology with no restrictions.

We have recently noticed that a co-founder of TON Labs (owner of the TON Venture LTD) [mentioned in a public Telegram chat](https://t.me/infotonchat/74971) that his company has an agreement with Telegram concerning the TON trademark (see the screenshot attached).

<img width="972" alt="Screen" src="https://user-images.githubusercontent.com/1449561/133646617-b5c1b1a9-ee3e-4d55-9f0c-8bad4487457d.png">

Also, there is a link to a [public source](https://storage.courtlistener.com/recap/gov.uscourts.nysd.524448/gov.uscourts.nysd.524448.72.0.pdf) (see paragraph 178) reading that, in 2019, Telegram, as the owner of the “TON” trademark, granted TON Ventures a non-exclusive right to use it. 

Later a public Telegram channel [DeCenter](https://t.me/DeCenter) dedicated to blockchain and cryptocurrencies news published a [copy of the agreement](https://t.me/DeCenter/8253) (the file is attached) between TON Ventures and Telegram under which TON Ventures receives a non-exclusive right to use the “TON” trademark but promises not to apply for or obtain any registration of it (see paragraph 4.c). If this agreement is valid, TON Ventures acted in bad faith when it registered the trademark knowing that Telegram remains the only rightful ownership.

[Trademark_Agreement — @DeCenter.pdf](https://github.com/newton-blockchain/TIPs/files/7179327/Trademark_Agreement.%40DeCenter.pdf)

Therefore, with an aim to secure the ability of open communities all over the world to run TON-based projects, we kindly ask you to confirm the validity of the Trademark License Agreement between Telegram and TON Ventures published by DeCenter. We would also appreciate further information on the existence of any other agreements, documentation or registrations regarding the “TON” trademark.

Also, we would highly appreciate, if you share your opinion on the trademark registration performed by TON Ventures LTD, as well as on their activities aimed at limiting the ability of open communities to continue working on the TON technology.

Your answers may significantly help us, as well as all other interested parties, to protect their right to utilize the technological heritage of the Telegram team in the blockchain area.

**Comment by toozwu** [comment]
toncommunity.org agrees with the above view.
