### ISSUE TITLE
Check WalletID uniquiness within TON Crystal network on creating

### ISSUE THREAD

**Issue by ayerix** [ton-blockchain/TIPs#40]
Problem is:
User can send TON Crystal coins instead of TON (without realizing that this is completely different coin) and send them to his TON wallet. If wallet with the same ID exists in TON Crystal network the transaction will be succeed and all the money goes to nowhere. We should protect users from misunderstanding. Nobody knows about the difference, about the other network with completely the same design, name, icon and the same wallet addresses, mistakes are inevitable unless wallets addresses would be separated from each other by prefix or uniquiness control within both networks. So you have 40 char for unique wallet ID, why IDs are equal in only several months of network operating? Users are not able to somehow distinguish they are on the wrong course and operating with wrong coins

**Comment by tolya-yanot** [comment]
There are no plans to change the address format.

A script to recover such erroneous transactions -  https://github.com/Custler/tc_Rescue
