### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by LmaoImo** [ton-blockchain/TIPs#41]
Hi, 

I've been trying to send TON to bridge contract to get TONCOIN on BSC but kept failing:
Ef9NXAIQs12t2qIZ-sRZ26D977H65Ol6DQeXc5_gUNaUys5r

Whenever I send it out, it will refund me instantly. 

Could you please help with this issue? 

Thanks a lot!

**Comment by sanygus** [comment]
if I made a transaction to the smart contract earlier (like previous swaps) than I created a transfer request on the page https://ton.org/bridge, how to return TONs?

**Comment by EmelyanenkoK** [comment]
@sanygus 
Please contact team of TON support volunteers in telegram @toncoin_help.

newton-blockchain/TIPs is not appropriate place for support issues, closing thread.

**Comment by sanygus** [comment]
Sorry to be out of place. Indeed, volunteers helped me. Thanks!
