### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by konak** [ton-blockchain/TIPs#51]
There is an issue subtracting transaction fee from receiver not from the sender

1. there was right 52 TON in my wallet
2. someone send me very small amount of TON to my wallet: 0.000009999 (0.00001)
3. storage fee for that transaction: 0.000013579
4. Now on my wallet there is 51.99999642 TON

Why fee is subtracted from my wallet if someone else is sending something to me ? Why that fee is not subtracted from sender wallet ? It will allow intruder to reduce amount of any wallet to zero ...

My wallet address: EQAqV4fgkrEVGjU-ekT29pnuf4EM2vYYml_UOFQNWXLIKM0T
Senders wallet address: EQCW1v0RwP31xMrDgUu0Qa18Z0YssSulsrhoDtZHpJ6p5s3J
Transaction: sZB8tyNwPdwziIXvITc3Mpupk8wQZ/niDVqjWd7RK5w=

**Comment by akifoq** [comment]
As you can see, `51.99999642` is exactly equal to `52 + 0.000009999 - 0.000013579`. That is, your wallet was credited by the inbound message value and after that the storage fee was subtracted from the balance. Please note that it's the storage fee being subtracted, not the transaction (i.e. gas + forwarding) fee. 

Storage fee is a payment to validators for storing your wallet data (e.g. public key) in the blockchain state. It's collected at any transaction on your wallet, and the payment is proportional to the time passed after the last collection. So you anyway were to pay those `0.000013579` TONs. If you hadn't received the message, you would have payed it after any attempt to send some funds from the wallet.

**Comment by konak** [comment]
Storage fee accepted, ok. But when you look at the wallet, you do not see that it is a storage fee. In mobile application when you open transfer details you see four fields:

Sender:
Transaction:
Fee:
Message:

Maybe there is a need to change the name of the field ? (Storage/Wallet update fee)

The other think is maybe there is a need to define the minimal transfer amount ? And that amount should not be less than all fees necessary to make that transfer.

What will happen if the same transfer will be done to wallet with no any TON at all (or amount is smaller than fees) ? It will become negative ? Is that Ok ?

**Comment by akifoq** [comment]
> The other think is maybe there is a need to define the minimal transfer amount ?
I see no reason to do that. 
> And that amount should not be less than all fees necessary to make that transfer
Storage fee is not a transfer fee, it's just collected at any transaction on your wallet.

> What will happen if the same transfer will be done to wallet with no any TON at all (or amount is smaller than fees) ?
It may become a frozen account. After that you are able to unfreeze it.

> Is that Ok ?
Yes. Incoming transfer just actualizes

**Comment by konak** [comment]
@akifoq thanks for your time and answers ! Wish you all the best !
