### ISSUE TITLE
DELETED

### ISSUE THREAD

**Issue by tondevelops** [ton-blockchain/TIPs#71]
TONCOIN is the first blockchain with a useful pool of services which is built around it: cloud storage, sites, vpn etc..
This adds the capability to give an equivalent for some amount of TONS, i.e:

1 TON: 1Gb of vpn traffic
3 TON: 200GB of weekly cloud storage and so on.

I propose here to define a standard way for dapps to give a 'value' to the coin basing this estimate on the price of the services deployed in the network.
This could help TON acquire a real money connotation, whenever someone is sending TONS he can say "You can buy 10 slice of bread with this"

A use case:
Whenever a dapp has to present the user a list with some default amounts to deposit\donate\give and wants to show reasonable values it should check the location of the user. (10€ in Germany buys less than 10€ in Poland, 1$ in Thailand buys more than 1$ in LA). The same holds for other money.
The dapp could instead use the above estimate and present to the user an amount which is 'reasonable' in terms of network value.

**Comment by sumatoreo** [comment]
I think that the price should be set by the service itself.

But for a guarantee, freeze funds in a special smart contract, especially when it comes to TON Storage
